---
title: "git_01"
author: "stella"
date: "October 3, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits
Our project will be done using a sequence of save and commits.

## First Verse 
<Put the first two verses of Jabberwocky by Lewis Carrol in this section>
`Twas brillig, and the slithy toves
  Did gyre and gimble in the wabe:
All mimsy were the borogoves,
  And the mome raths outgrabe
  
Put the first two verses of The Road Not Taken by Robert Frost here>
"Beware the Jabberwock, my son!
  The jaws that bite, the claws that catch!
Beware the Jubjub bird, and shun
  The frumious Bandersnatch!"
## Second Verse
<Put the first two verses of The Road Not Taken by Robert Frost here>

Two roads diverged in a yellow wood,
And sorry I could not travel both
And be one traveler, long I stood
And looked down one as far as I could
To where it bent in the undergrowth
## Third Verse
<Put the first two verses of The Walrus and the Carpenter here>
The sun was shining on the sea,
Shining with all his might:
He did his very best to make
The billows smooth and bright--
And this was odd, because it was
The middle of the night.
## Last Verse
<Put a short poem of your choice 8-20 lines,here>
